### PR TITLE
added support for head requests

### PR DESCRIPTION
**Pull request by zagreusinoz**
As noted in #5 this middleware needs to support head requests if it's going to be of use to save bandwidth.

I have made the update that will do this.

### CODE REVIEW

**Comment by matthewbdaly** [comment]
This pull request breaks the build, so please could you update the test suite to resolve this. Should be easy - it's just a case of setting up the request mock to expect to see the call to `method()`.

If you could also correct `recieve` to `receive` in `src/ETag.php` that would be great.

**Comment by matthewbdaly** [comment]
Once the build passes I'll merge in the pull request and do a new release.

**Comment by zagreusinoz** [comment]
I'm afraid I have no idea how to do that, not having used mockery before.  I can't assert shouldReceive on the request object so I'm not sure how to do that I'm afraid ...

**Comment by matthewbdaly** [comment]
Ok, in the second of the two tests the middleware gets passed mocks of the request and response objects. At present the test is failing because there are unexpected method calls being made on the mock.

For instance, if I pass a mock of the request  object into the middleware as `$request`, and the middleware calls `$request->foo()`, I need to tell Mockery to expect to see this when setting up the mock, as in this example:

```php
$request = m::mock('Illuminate\HttpRequest');
$request->shouldReceive('foo');
```

If you need to assert it's called a specific number of times, you can chain `once()`, `twice()` or `times(3)` as appropriate.

You can also specify arguments like this:

```php
$request->shouldReceive('foo')->with('bar');
```

To check specifically for `$request->foo('bar');`.

**Comment by matthewbdaly** [comment]
You can also specify a response, as in this example:

```php
$request->shouldReceive('foo')->andReturn($fooObject);
```

It's all chainable, so you can use all these together:

```php
$request->shouldReceive('foo')->with('bar')->once()->andReturn($fooObject);
```

Mockery isn't hard to pick up, and once you know how to use it, it'll make it a lot easier to write proper unit tests. If you get stuck, give me a shout and I'll be happy to help.

**Comment by zagreusinoz** [comment]
Ok, thanks for the tips.  It passes the tests now.

**Comment by matthewbdaly** [comment]
Cheers, I've merged it in and created a new release.

**Pull request merged**
